[project]
name = "authorize-allowance"
authors = ["Authorize Allowance Team"]
description = "A smart contract system for flexible and secure digital asset authorization"
telemetry = false
requirements = []
[contracts.allowance-controller]
path = "contracts/allowance-controller.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
